#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MoocMall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

# logging
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
